"""
Utility functions for data handling
"""

import pandas as pd


def initialize_data():
    """Initialize sample application data"""
    return pd.DataFrame(
        {
            "application_id": list(range(1001, 1011)),
            "name": [
                "John Doe",
                "Jane Smith",
                "Robert Johnson",
                "Maria Garcia",
                "Wei Chen",
                "Fatima Ahmed",
                "Carlos Rodriguez",
                "Aisha Patel",
                "Viktor Petrov",
                "Olivia Kim",
            ],
            "date_of_birth": [
                "1990-05-16",
                "1992-08-23",
                "1985-11-30",
                "1988-03-21",
                "1995-02-14",
                "1987-07-09",
                "1993-12-05",
                "1991-04-18",
                "1989-09-27",
                "1994-01-12",
            ],
            "passport_number": [
                "AB123459",
                "CD789012",
                "EF345678",
                "GH901234",
                "IJ567890",
                "KL123456",
                "MN789012",
                "OP345678",
                "QR901234",
                "ST567890",
            ],
            "nationality": [
                "USA",
                "UK",
                "Canada",
                "Mexico",
                "China",
                "Egypt",
                "Brazil",
                "India",
                "Russia",
                "South Korea",
            ],
            "visa_type": [
                "Tourist",
                "Student",
                "Work",
                "Family",
                "Tourist",
                "Business",
                "Student",
                "Work",
                "Tourist",
                "Business",
            ],
            "status": [
                "Not Started",
                "In Progress",
                "Completed",
                "Not Started",
                "In Progress",
                "Not Started",
                "In Progress",
                "Completed",
                "Not Started",
                "In Progress",
            ],
            "submission_date": pd.date_range(start="2025-01-01", periods=10)
            .strftime("%Y-%m-%d")
            .tolist(),
            "personal_info_status": [
                "Pending",
                "Approved",
                "Approved",
                "Pending",
                "Feedback",
                "Pending",
                "Rejected",
                "Approved",
                "Pending",
                "Feedback",
            ],
            "document_status": [
                "Pending",
                "Pending",
                "Approved",
                "Pending",
                "Approved",
                "Pending",
                "Rejected",
                "Approved",
                "Pending",
                "Feedback",
            ],
            "criminal_history_status": [
                "Pending",
                "Pending",
                "Approved",
                "Pending",
                "Pending",
                "Pending",
                "Rejected",
                "Approved",
                "Pending",
                "Pending",
            ],
            "officer_notes": [
                "",
                "Needs additional financial proof",
                "All documents verified",
                "",
                "Passport expiry date concern",
                "",
                "Criminal record found",
                "Approved after verification",
                "",
                "Financial documents need clarification",
            ],
        }
    )
